sudo: true

language: python

python:
  - "2.7"
  - "3.6"
  - "pypy"

install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
  - pip install -e git+https://github.com/peteut/nose2-cprof.git#egg=nose2cprof

script:
  - make test
